### ISSUE TITLE
Cased repo name causing user content issues

### ISSUE THREAD

**Issue by samuelli** [webcomponents/beta#571]
This isn't treated as a valid dependency:
https://user-content-dot-custom-elements-staging.appspot.com/Maps4HTML/Web-Map-Custom-Element/28ec34c3887371037dbba6fe1030cb94777ce0d1/Web-Map-Custom-Element/web-map.html

This works:
https://user-content-dot-custom-elements-staging.appspot.com/Maps4HTML/Web-Map-Custom-Element/28ec34c3887371037dbba6fe1030cb94777ce0d1/web-map-custom-element/web-map.html

**Comment by andymutton** [comment]
Fixed by #572 & #574.

**Comment by prushforth** [comment]
Hi Sam, I think there is still an issue with repo name casing.  When I export a jsfiddle and look at some of the responses, here is one that stands out for me: "Web-Map-Custom-Element is not a valid dependency for maps4html/web-map-custom-element#310a839144be01f977fff53b48a58eb3d522fbfe"
